[theme]
# Primary accent color
primaryColor="#1f77b4"  # Muted blue

# Background color
backgroundColor="#f0f2f6" # Light grey

# Secondary background color for elements like sidebar, expanders
secondaryBackgroundColor="#ffffff" # White

# Text color
textColor="#31333F"

# Font family (sans serif, serif, or monospace)
font="sans serif"

